- name: copy artifact
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: extract artifact
  unarchive:
    src: /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: install dependencies
  become: yes
  npm:
    path: /home/ubuntu/backend
    state: present

# - name: stop default
#   shell: |
#     pm2 stop default

- name: run server
  shell: |
    pm2 start npm --name "backend" -- start